from __future__ import annotations
import json
import os
import re
from typing import Any, Dict, List, Optional

from fastapi import APIRouter, HTTPException
from pydantic import BaseModel

from session_store import get_session

router = APIRouter(tags=["ai_insights"])

# ── Vertex AI Gemini configuration ────────────────────────────────────────────
# Loads from backend/.env if present (auto-generated by scripts/setup_gcp.sh)
def _load_env_file():
    from pathlib import Path
    env_path = Path(__file__).parent.parent / ".env"
    if env_path.exists():
        for line in env_path.read_text().splitlines():
            line = line.strip()
            if not line or line.startswith("#") or "=" not in line:
                continue
            k, v = line.split("=", 1)
            os.environ.setdefault(k.strip(), v.strip().strip('"').strip("'"))


_load_env_file()

PROJECT    = os.environ.get("GEMINI_VERTEX_PROJECT",  "gen-lang-client-0226029743")
LOCATION   = os.environ.get("GEMINI_VERTEX_LOCATION", "us-central1")
MODEL_NAME = os.environ.get("GEMINI_MODEL",           "gemini-2.5-pro")

_MODEL = None
_MODEL_TRIED = False


def _get_model():
    """Lazy-init Vertex Gemini model. Uses Application Default Credentials.
    Set up ADC by running: scripts/setup_gcp.sh (or `gcloud auth application-default login`).
    _MODEL_TRIED flag prevents repeated init attempts on failure."""
    global _MODEL, _MODEL_TRIED
    if _MODEL is not None:
        return _MODEL
    if _MODEL_TRIED:
        return None
    _MODEL_TRIED = True
    # NOTE: catch BaseException, not Exception. Some import-time failures in
    # the vertexai → google.auth → cryptography chain raise BaseException
    # subclasses (e.g. pyo3 PanicException) on systems with broken rust
    # bindings. We don't want a borked local env to 500 the status endpoint.
    try:
        from vertexai import init as vertex_init
        from vertexai.generative_models import GenerativeModel
        vertex_init(project=PROJECT, location=LOCATION)
        _MODEL = GenerativeModel(MODEL_NAME)
        print(f"[ai_insights] Vertex AI Gemini ready: {PROJECT}/{LOCATION}/{MODEL_NAME}")
        return _MODEL
    except BaseException as e:
        print(f"[ai_insights] Vertex init failed: {e}")
        print(f"[ai_insights] To enable AI insights, run: bash scripts/setup_gcp.sh")
        return None


def _strip_fences(text: str) -> str:
    """Remove markdown JSON fences from Gemini output."""
    if not text: return ""
    text = re.sub(r"^```(?:json)?\s*", "", text.strip())
    text = re.sub(r"\s*```$", "", text)
    return text.strip()


def _gemini_generate(prompt: str) -> Optional[str]:
    model = _get_model()
    if model is None:
        return None
    try:
        resp = model.generate_content(prompt)
        return _strip_fences(resp.text or "")
    except BaseException as e:
        # Same rationale as _get_model — never let an LLM-stack hiccup
        # escape past this layer.
        print(f"[ai_insights] generation error: {e}")
        return None


def _build_rich_context(sess) -> str:
    """Build detailed data context for prompts including drilldowns."""
    bits = []
    overall = sess.get("overall_result")
    if overall is not None:
        score = getattr(overall, "score", None) or (overall.get("score") if isinstance(overall, dict) else None)
        level = getattr(overall, "level", None) or (overall.get("level") if isinstance(overall, dict) else None)
        bits.append(f"Overall maturity: {score} ({level})")
    kpi_assessment = sess.get("kpi_assessment")
    if kpi_assessment is not None:
        kpi_results = getattr(kpi_assessment, "kpi_results", None) or {}
        for kid, kr in list(kpi_results.items())[:12]:
            bits.append(f"- {getattr(kr,'label','')}: actual={getattr(kr,'actual',None)}, "
                        f"benchmark={getattr(kr,'benchmark',None)}, score={getattr(kr,'score',None)}")
    qre = sess.get("text_qre_confirmed") or {}
    if qre:
        bits.append(f"Confirmed QRE scores: {json.dumps(qre)}")
    discovery = sess.get("discovery_qre") or {}
    if discovery:
        bits.append(f"Discovery answers: {json.dumps(discovery)[:1000]}")
    return "\n".join(bits)


def _build_prompt(sess, force_refresh: bool = False) -> str:
    """Main 5-rule prompt for end-to-end insights generation."""
    context = _build_rich_context(sess)
    return f"""You are a procurement consultant analysing a maturity assessment.

DATA CONTEXT:
{context}

RULES:
1. Ground every recommendation in the data above. Do not invent metrics.
2. Cite specific KPI gaps (e.g. "TAT 78d vs 45d benchmark") in evidence.
3. Recommendations must be specific actions (not "improve X" — "Roll out catalog buying for top-20 indirect categories").
4. Severity = high if score < 2 OR gap_pct > 50%; medium if 2 ≤ score < 3 OR gap_pct 20-50%; else low.
5. Output STRICT JSON ONLY — no markdown, no commentary outside the JSON.

JSON SCHEMA:
{{
  "summary": "2-3 sentence executive summary of maturity state",
  "strengths": ["bullet points of what's working"],
  "gaps": ["bullet points of biggest gaps with KPI evidence"],
  "priorities": ["top 4 actions for the next 6 months, specific and outcome-linked"],
  "risk_flags": ["operational/compliance/savings risks visible in data"],
  "insight_cards": [
    {{"title": "...", "description": "...", "category": "efficiency|effectiveness|risk|compliance",
      "severity": "high|medium|low", "value": null, "benchmark": null}}
  ]
}}
"""


def _build_tab_prompt(sess, context_name: str) -> str:
    """3 context variants: kpi_overview, rca, offerings.

    The output JSON shape MUST match what `frontend/src/components/results/
    AiInsightsMini.tsx` renders, otherwise the AI panel renders blank.
    """
    base_context = _build_rich_context(sess)
    if context_name == "kpi_overview":
        return f"""You are a procurement consultant analysing this maturity assessment.

DATA CONTEXT:
{base_context}

Pick the 2–3 best-performing KPIs (top performers) and the 2–3 worst (urgent gaps).
For each gap, write a one-sentence root cause inferred from the data and a one-
sentence concrete fix. Add 3–4 30-day priorities that are specific verbs (e.g.
"Roll out catalog buying for top-20 indirect categories"), not generic advice.

OUTPUT STRICT JSON, no markdown, no commentary outside the JSON:
{{
  "headline": "1-2 sentence executive overview of KPI scorecard state",
  "top_performers": [
    {{"kpi": "PR-to-PO TAT", "insight": "9 days vs benchmark 9d — at par"}}
  ],
  "urgent_gaps": [
    {{"kpi": "RC adoption (volume)", "root_cause": "...", "fix": "..."}}
  ],
  "30_day_priorities": ["action 1", "action 2", "action 3"],
  "source": "vertex-gemini"
}}
"""
    if context_name == "rca":
        return f"""You are a procurement consultant doing root-cause analysis.

DATA CONTEXT:
{base_context}

For the lowest-scoring KPIs, hypothesise data-grounded root causes.
Each root_cause has: issue (1 line), evidence (numeric or pattern from the
data), intervention (concrete action), urgency ("High"/"Medium"/"Low" —
High when the KPI score is < 2 OR gap exceeds 30%).

OUTPUT STRICT JSON, no markdown:
{{
  "rca_summary": "2-3 sentence narrative tying root causes together",
  "root_causes": [
    {{"issue": "...", "evidence": "...", "intervention": "...", "urgency": "High"}}
  ],
  "intervention_priority": [
    {{"area": "...", "rationale": "...", "expected_impact": "e.g. RC coverage +20pp in 6 months"}}
  ],
  "source": "vertex-gemini"
}}
"""
    if context_name == "offerings":
        return f"""You are a procurement transformation lead matching gaps to offerings.

DATA CONTEXT:
{base_context}

Recommend 3–5 transformation offerings drawn from this catalogue
(operating-model design, P2P automation, sourcing-as-a-service, category
strategy refresh, supplier risk management, spend analytics, contract
lifecycle management). Rank them with priority 1 (highest) to N. For each,
list the KPI ids it lifts (kpi_links), and the expected business benefit.

OUTPUT STRICT JSON, no markdown:
{{
  "recommendation_summary": "2-3 sentences explaining why these offerings",
  "top_offerings": [
    {{"offering": "...", "priority": 1, "rationale": "...",
      "kpi_links": ["RC adoption (volume)", "Tail spend"], "expected_benefit": "..."}}
  ],
  "quick_start": "1-sentence first move to capture momentum",
  "source": "vertex-gemini"
}}
"""
    return f"""You are a procurement consultant. Context:\n{base_context}\nReturn STRICT JSON with 'summary', 'key_points', 'recommendations'."""


def _g(o, k, default=None):
    if o is None: return default
    if hasattr(o, k): return getattr(o, k)
    if isinstance(o, dict): return o.get(k, default)
    return default


def _fmt_kpi_value(kr) -> str:
    """Render a KPI's actual in human-friendly units."""
    actual = _g(kr, "actual")
    unit   = _g(kr, "unit", "")
    if actual is None:
        return "n/a"
    if unit == "%":     return f"{round(actual * 100)}%"
    if unit == "days":  return f"{round(actual)} days"
    if unit == "₹ Cr":  return f"₹{round(actual, 1)} Cr"
    return f"{round(actual, 2)}"


def _rule_based_fallback(sess) -> Dict[str, Any]:
    """Generate useful insights from session data without an LLM.

    Reads dim_results + kpi_assessment, picks out the worst-performing
    KPIs, lowest-scoring dimensions and confirmed QRE answers, and
    writes structured insights mirroring the schema the LLM would have
    produced. The deployed app uses this whenever Vertex calls fail
    or the response can't be parsed."""
    overall      = sess.get("overall_result")
    dim_results  = sess.get("dim_results") or []
    ka           = sess.get("kpi_assessment")
    engagement   = sess.get("engagement") or {}

    overall_score = _g(overall, "score")
    overall_level = _g(overall, "level", "Insufficient")
    client = engagement.get("client_name", "the client")
    industry = engagement.get("industry", "")

    # ── Per-KPI sort: lowest score first, available only ───────────────
    kpi_results = _g(ka, "kpi_results") or {}
    kpis_sorted = sorted(
        ((kid, kr) for kid, kr in kpi_results.items() if _g(kr, "available", True)),
        key=lambda p: (_g(p[1], "score", 5), -float(_g(p[1], "weight", 0) or 0)),
    )

    # ── Strengths: KPIs scoring >= 3 ───────────────────────────────────
    strengths: List[str] = []
    for kid, kr in kpis_sorted:
        score = _g(kr, "score", 0)
        if score and score >= 3:
            strengths.append(
                f"{_g(kr, 'label', kid)} at {_fmt_kpi_value(kr)} "
                f"(benchmark {_format_benchmark(kr)}) — {_g(kr, 'score_label', '')}."
            )
    if not strengths and overall_score and overall_score >= 2:
        strengths.append(f"Overall {overall_level} maturity ({overall_score}/4.0) — coverage in place.")
    if not strengths:
        strengths.append("Data ingestion and KPI computation completed end-to-end.")

    # ── Gaps: KPIs scoring < 2.5, with concrete numbers ─────────────────
    gaps: List[str] = []
    for kid, kr in kpis_sorted:
        score = _g(kr, "score", 5)
        if score and score < 2.5:
            gaps.append(
                f"{_g(kr, 'label', kid)} at {_fmt_kpi_value(kr)} vs benchmark "
                f"{_format_benchmark(kr)} — {_g(kr, 'score_label', '')}."
            )

    # Lowest dimensions
    dim_sorted = sorted(
        (d for d in dim_results if _g(d, "score") is not None),
        key=lambda d: _g(d, "score", 5),
    )
    for d in dim_sorted[:3]:
        score = _g(d, "score")
        if score and score < 2.5:
            gaps.append(f"Dimension '{_g(d, 'name', '')}' scoring {score}/4 — focus area.")

    # ── Priorities: action-oriented from the worst 4 KPIs ──────────────
    priorities = _ACTIONS_BY_KPI
    actions: List[str] = []
    for kid, kr in kpis_sorted[:4]:
        score = _g(kr, "score", 5)
        if score and score < 3:
            actions.append(priorities.get(kid, f"Address {_g(kr, 'label', kid)} gap with a 90-day action plan."))
    if not actions:
        actions = [
            "Sustain current maturity by codifying the practices behind your top KPIs.",
            "Expand coverage by adding the data sources currently marked unavailable.",
            "Set quarterly targets for the next assessment cycle.",
        ]

    # ── Risk flags ─────────────────────────────────────────────────────
    risk_flags: List[str] = []
    for kid, kr in kpi_results.items():
        score = _g(kr, "score", 5)
        if score and score <= 1.5:
            risk_flags.append(f"{_g(kr, 'label', kid)} significantly below benchmark — operational risk.")
    if not risk_flags:
        risk_flags.append("No high-severity risk signals in the computed KPIs.")

    # ── Insight cards: one per gap, severity-keyed ─────────────────────
    insight_cards: List[Dict[str, Any]] = []
    for kid, kr in kpis_sorted[:6]:
        score = _g(kr, "score", 5)
        if score is None:
            continue
        severity = "high" if score < 2 else "medium" if score < 3 else "low"
        category = _CATEGORY_BY_BUCKET.get(_g(kr, "bucket", ""), "effectiveness")
        insight_cards.append({
            "title":       _g(kr, "label", kid),
            "description": _ACTIONS_BY_KPI.get(kid, "Review this KPI in the configure step."),
            "category":    category,
            "severity":    severity,
            "value":       _g(kr, "actual"),
            "benchmark":   _g(kr, "benchmark"),
        })

    summary = (
        f"{client} scored {overall_score or 'n/a'} ({overall_level}) overall"
        + (f" in the {industry} reference set" if industry else "")
        + f". {len(strengths)} strength(s) and {len(gaps)} gap(s) identified across the procurement maturity model."
    )

    return {
        "summary":       summary,
        "strengths":     strengths[:6],
        "gaps":          gaps[:6],
        "priorities":    actions[:4],
        "risk_flags":    risk_flags[:4],
        "insight_cards": insight_cards,
        "_engine":       "rule-based",
    }


def _format_benchmark(kr) -> str:
    """Format the benchmark value the same way the actual is rendered."""
    bench = _g(kr, "benchmark")
    unit  = _g(kr, "unit", "")
    if bench is None: return "n/a"
    if unit == "%":     return f"{round(bench * 100)}%"
    if unit == "days":  return f"{round(bench)} days"
    if unit == "₹ Cr":  return f"₹{round(bench, 1)} Cr"
    return f"{round(bench, 2)}"


_CATEGORY_BY_BUCKET: Dict[str, str] = {
    "Efficiency":        "efficiency",
    "Effectiveness":     "effectiveness",
    "Vendor Management": "effectiveness",
    "Risk":              "risk",
}

# Concrete, action-oriented recommendations keyed by KPI id.
_ACTIONS_BY_KPI: Dict[str, str] = {
    "tat_pr_to_po":       "Roll out catalog buying for the top 20 indirect categories — typical 30–45% TAT reduction.",
    "rc_adoption_volume": "Push rate-contract coverage on top-spend categories with a CFO-sponsored compliance gate.",
    "otd":                "Tier strategic suppliers with monthly OTD scorecards and joint recovery plans for the worst 5.",
    "savings_per_lpo":    "Re-baseline LPO references, track validated savings via finance, and challenge top 10 categories.",
    "pac_3way_match":     "Enforce systemic 3-way match with exception SLAs; target >95% on goods invoices.",
    "emergency_pr_pct":   "Introduce demand forecasting + safety-stock review for the top 5 categories driving emergency PRs.",
    "tail_spend":         "Consolidate tail vendors; target 80/20 to top 50 suppliers via a sourcing-as-a-service play.",
    "spend_per_fte":      "Increase spend managed per FTE through shared services + automation (touchless PO target 60%).",
}


_ROOT_CAUSES_BY_KPI: Dict[str, Dict[str, str]] = {
    "tat_pr_to_po": {
        "issue":        "Slow PR-to-PO turnaround",
        "intervention": "Roll out catalog buying + auto-approval thresholds for the top 20 indirect categories.",
    },
    "rc_adoption_volume": {
        "issue":        "Low rate-contract coverage",
        "intervention": "CFO-sponsored compliance gate that routes top-spend categories through RC by default.",
    },
    "otd": {
        "issue":        "Suppliers missing delivery dates",
        "intervention": "Strategic-supplier scorecards with monthly OTD reviews and joint recovery plans.",
    },
    "savings_per_lpo": {
        "issue":        "Negotiated savings leak at PO creation",
        "intervention": "Re-baseline LPO references and validate savings via finance at PO commit.",
    },
    "pac_3way_match": {
        "issue":        "3-way match exceptions",
        "intervention": "Enforce systemic 3-way match with exception SLAs and weekly clearance review.",
    },
    "emergency_pr_pct": {
        "issue":        "High emergency-PR rate",
        "intervention": "Demand forecasting + safety-stock review for the top 5 emergency-driver categories.",
    },
    "tail_spend": {
        "issue":        "Long tail of low-spend vendors",
        "intervention": "Consolidate the tail; target 80/20 to top 50 suppliers via sourcing-as-a-service.",
    },
    "spend_per_fte": {
        "issue":        "Procurement leverage below benchmark",
        "intervention": "Scale shared services + automation; target touchless-PO rate of 60%+.",
    },
}


_OFFERINGS_CATALOGUE = [
    {"offering": "Operating-model and organisation redesign",
     "kpi_links": ["spend_per_fte", "tat_pr_to_po"],
     "rationale": "Reshape the procurement org to lift productivity and accountability.",
     "expected_benefit": "Spend/FTE +20% in 12 months."},
    {"offering": "Sourcing-as-a-service for tail spend",
     "kpi_links": ["tail_spend", "rc_adoption_volume"],
     "rationale": "Externalise tail-vendor management to consolidate vendors and fund category programmes.",
     "expected_benefit": "Tail spend -10pp in 9 months."},
    {"offering": "P2P automation and 3-way match enforcement",
     "kpi_links": ["pac_3way_match", "tat_pr_to_po"],
     "rationale": "Push touchless POs and tighten match controls to cut TAT and exceptions.",
     "expected_benefit": "Touchless-PO rate to 60%+, TAT down 30%."},
    {"offering": "Category strategy refresh",
     "kpi_links": ["rc_adoption_volume", "savings_per_lpo"],
     "rationale": "Reset top-spend categories with rate contracts and demand consolidation.",
     "expected_benefit": "RC coverage +20pp, 4-6% category savings."},
    {"offering": "Supplier-risk and performance management",
     "kpi_links": ["otd"],
     "rationale": "Tier suppliers, scorecard the strategic ones, and run joint OTD recovery.",
     "expected_benefit": "OTD +5pp; supply disruptions down 30%."},
    {"offering": "Spend analytics + AI insights platform",
     "kpi_links": ["tail_spend", "spend_per_fte"],
     "rationale": "Foundational visibility — without it, every other lever is half-blind.",
     "expected_benefit": "Decision lead time cut by 50%."},
]


def _urgency(score) -> str:
    if score is None: return "Low"
    return "High" if score < 2 else "Medium" if score < 3 else "Low"


def _tab_rule_based_fallback(sess, context_name: str) -> Dict[str, Any]:
    """Per-tab fallback that pulls the same data view as the LLM prompt and
    returns the exact shape AiInsightsMini renders."""
    main = _rule_based_fallback(sess)
    ka = sess.get("kpi_assessment")
    kpi_results = _g(ka, "kpi_results") or {}
    kpis_sorted = sorted(
        ((kid, kr) for kid, kr in kpi_results.items() if _g(kr, "available", True)),
        key=lambda p: (_g(p[1], "score", 5), -float(_g(p[1], "weight", 0) or 0)),
    )

    if context_name == "kpi_overview":
        top = []
        for kid, kr in reversed(kpis_sorted):
            score = _g(kr, "score", 0)
            if score and score >= 3:
                top.append({
                    "kpi":     _g(kr, "label", kid),
                    "insight": f"{_fmt_kpi_value(kr)} vs benchmark {_format_benchmark(kr)} — {_g(kr, 'score_label', '')}.",
                })
            if len(top) == 3:
                break
        urgent = []
        for kid, kr in kpis_sorted[:3]:
            score = _g(kr, "score", 0)
            if score and score < 2.5:
                urgent.append({
                    "kpi":        _g(kr, "label", kid),
                    "root_cause": f"Actual {_fmt_kpi_value(kr)} vs benchmark {_format_benchmark(kr)}.",
                    "fix":        _ACTIONS_BY_KPI.get(kid, "Build a 90-day action plan."),
                })
        return {
            "headline":          main["summary"],
            "top_performers":    top or [{"kpi": "—", "insight": "No KPI scoring above 3 yet — focus on the gaps."}],
            "urgent_gaps":       urgent,
            "30_day_priorities": main["priorities"][:4],
            "source":            "rule-based",
        }

    if context_name == "rca":
        causes = []
        for kid, kr in kpis_sorted[:5]:
            score = _g(kr, "score", 0)
            if score is None or score >= 3:
                continue
            template = _ROOT_CAUSES_BY_KPI.get(kid, {})
            causes.append({
                "issue":        template.get("issue", _g(kr, "label", kid)),
                "evidence":     f"{_g(kr, 'label', kid)} at {_fmt_kpi_value(kr)} vs benchmark {_format_benchmark(kr)}.",
                "intervention": template.get("intervention", _ACTIONS_BY_KPI.get(kid, "Review with category lead.")),
                "urgency":      _urgency(score),
            })
        priorities = []
        for kid, kr in kpis_sorted[:3]:
            score = _g(kr, "score", 0)
            if score is None or score >= 3:
                continue
            priorities.append({
                "area":            _g(kr, "label", kid),
                "rationale":       _ACTIONS_BY_KPI.get(kid, "Largest gap to benchmark in this bucket."),
                "expected_impact": "Move from " + (_g(kr, "score_label") or "Foundation") + " toward Advanced in 6–9 months.",
            })
        return {
            "rca_summary":         "Lowest-scoring KPIs cluster around rate-contract coverage and tail-vendor sprawl. "
                                   "Each root cause below is grounded in the actual numbers from this assessment.",
            "root_causes":         causes,
            "intervention_priority": priorities,
            "source":              "rule-based",
        }

    if context_name == "offerings":
        # Score each offering by how many of its KPI links are in the top gaps
        gap_kids = {kid for kid, kr in kpis_sorted[:5] if (_g(kr, "score", 5) or 5) < 3}
        scored = []
        for off in _OFFERINGS_CATALOGUE:
            relevant = sum(1 for k in off["kpi_links"] if k in gap_kids)
            scored.append((relevant, off))
        scored.sort(key=lambda p: -p[0])
        top_offs = []
        for prio, (_relevance, off) in enumerate(scored[:5], start=1):
            top_offs.append({
                "offering":         off["offering"],
                "priority":         prio,
                "rationale":        off["rationale"],
                "kpi_links":        [_g(kpi_results.get(k), "label", k) for k in off["kpi_links"]],
                "expected_benefit": off["expected_benefit"],
            })
        return {
            "recommendation_summary": "These offerings are sequenced to attack the largest gaps first while building the "
                                      "data backbone needed to sustain improvements.",
            "top_offerings":          top_offs,
            "quick_start":            "Stand up a 90-day RC expansion sprint on the top 3 spend categories — fastest visible impact.",
            "source":                 "rule-based",
        }

    return {
        "headline":          main["summary"],
        "top_performers":    [],
        "urgent_gaps":       [],
        "30_day_priorities": main["priorities"],
        "source":            "rule-based",
    }


class AiInsightsPayload(BaseModel):
    force_refresh: bool = False


@router.post("/session/{session_id}/results/ai-insights")
def generate_ai_insights(session_id: str, payload: AiInsightsPayload):
    sess = get_session(session_id)
    if not payload.force_refresh and sess.get("ai_insights"):
        return sess["ai_insights"]
    prompt = _build_prompt(sess, payload.force_refresh)
    raw = _gemini_generate(prompt)
    if raw:
        try:
            data = json.loads(raw)
        except Exception as e:
            data = _rule_based_fallback(sess)
            data["_parse_error"] = str(e)
    else:
        data = _rule_based_fallback(sess)
    sess["ai_insights"] = data
    return data


@router.get("/session/{session_id}/results/ai-insights/status")
def ai_insights_status(session_id: str):
    sess = get_session(session_id)
    return {
        "has_insights": sess.get("ai_insights") is not None,
        "vertex_available": _get_model() is not None,
    }


class AiTabPayload(BaseModel):
    context: str  # kpi_overview, rca, offerings
    force_refresh: bool = False


@router.post("/session/{session_id}/results/ai-tab-insights")
def generate_tab_insights(session_id: str, payload: AiTabPayload):
    sess = get_session(session_id)
    cache_key = f"ai_tab_insights_{payload.context}"
    if not payload.force_refresh and sess.get(cache_key):
        return sess[cache_key]
    prompt = _build_tab_prompt(sess, payload.context)
    raw = _gemini_generate(prompt)
    if raw:
        try:
            data = json.loads(raw)
            # Defensive: tag source even if Gemini omitted it. The frontend
            # uses `data.source === "vertex-gemini"` to decide between the
            # "Gemini · grounded" chip and the "Rule-based" chip.
            data.setdefault("source", "vertex-gemini")
        except Exception:
            data = _tab_rule_based_fallback(sess, payload.context)
    else:
        data = _tab_rule_based_fallback(sess, payload.context)
    sess[cache_key] = data
    return data


@router.post("/session/{session_id}/results/ai-buying-categories")
def generate_buying_categories(session_id: str):
    """Gemini-powered material group → buying category structure."""
    sess = get_session(session_id)
    if sess.get("ai_buying_categories"):
        return sess["ai_buying_categories"]
    dfs = sess.get("dataframes") or {}
    po_df = dfs.get("po_df")
    if po_df is None:
        raise HTTPException(status_code=400, detail="No PO data — upload first.")
    col_map = sess.get("final_col_map") or {}
    from routers.kpi_dashboard import _get_po_col
    mg_col = _get_po_col(po_df, "material_group", col_map)
    desc_col = _get_po_col(po_df, "material_group_desc", col_map)
    if not mg_col:
        raise HTTPException(status_code=400, detail="Material group column not found.")
    sample = po_df[[mg_col]].drop_duplicates().head(50).values.tolist()
    prompt = f"""Group the following SAP material groups into 5-7 logical buying categories.

MATERIAL GROUPS:
{sample}

OUTPUT STRICT JSON:
{{
  "categories": [
    {{"name": "...", "description": "...", "material_groups": ["MG001", ...]}}
  ]
}}
"""
    raw = _gemini_generate(prompt)
    if raw:
        try: data = json.loads(raw)
        except Exception: data = {"categories": []}
    else:
        data = {"categories": []}
    sess["ai_buying_categories"] = data
    return data
