from __future__ import annotations
import json
import os
import re
from typing import Any, Dict, List, Optional

from fastapi import APIRouter, HTTPException
from pydantic import BaseModel

from session_store import get_session

router = APIRouter(tags=["ai_insights"])

# ── Vertex AI Gemini configuration ────────────────────────────────────────────
# Loads from backend/.env if present (auto-generated by scripts/setup_gcp.sh)
def _load_env_file():
    from pathlib import Path
    env_path = Path(__file__).parent.parent / ".env"
    if env_path.exists():
        for line in env_path.read_text().splitlines():
            line = line.strip()
            if not line or line.startswith("#") or "=" not in line:
                continue
            k, v = line.split("=", 1)
            os.environ.setdefault(k.strip(), v.strip().strip('"').strip("'"))


_load_env_file()

PROJECT    = os.environ.get("GEMINI_VERTEX_PROJECT",  "gen-lang-client-0226029743")
LOCATION   = os.environ.get("GEMINI_VERTEX_LOCATION", "us-central1")
MODEL_NAME = os.environ.get("GEMINI_MODEL",           "gemini-2.5-pro")

_MODEL = None
_MODEL_TRIED = False


def _get_model():
    """Lazy-init Vertex Gemini model. Uses Application Default Credentials.
    Set up ADC by running: scripts/setup_gcp.sh (or `gcloud auth application-default login`).
    _MODEL_TRIED flag prevents repeated init attempts on failure."""
    global _MODEL, _MODEL_TRIED
    if _MODEL is not None:
        return _MODEL
    if _MODEL_TRIED:
        return None
    _MODEL_TRIED = True
    try:
        from vertexai import init as vertex_init
        from vertexai.generative_models import GenerativeModel
        vertex_init(project=PROJECT, location=LOCATION)
        _MODEL = GenerativeModel(MODEL_NAME)
        print(f"[ai_insights] Vertex AI Gemini ready: {PROJECT}/{LOCATION}/{MODEL_NAME}")
        return _MODEL
    except Exception as e:
        print(f"[ai_insights] Vertex init failed: {e}")
        print(f"[ai_insights] To enable AI insights, run: bash scripts/setup_gcp.sh")
        return None


def _strip_fences(text: str) -> str:
    """Remove markdown JSON fences from Gemini output."""
    if not text: return ""
    text = re.sub(r"^```(?:json)?\s*", "", text.strip())
    text = re.sub(r"\s*```$", "", text)
    return text.strip()


def _gemini_generate(prompt: str) -> Optional[str]:
    model = _get_model()
    if model is None:
        return None
    try:
        resp = model.generate_content(prompt)
        return _strip_fences(resp.text or "")
    except Exception as e:
        print(f"[ai_insights] generation error: {e}")
        return None


def _build_rich_context(sess) -> str:
    """Build detailed data context for prompts including drilldowns."""
    bits = []
    overall = sess.get("overall_result")
    if overall is not None:
        score = getattr(overall, "score", None) or (overall.get("score") if isinstance(overall, dict) else None)
        level = getattr(overall, "level", None) or (overall.get("level") if isinstance(overall, dict) else None)
        bits.append(f"Overall maturity: {score} ({level})")
    kpi_assessment = sess.get("kpi_assessment")
    if kpi_assessment is not None:
        kpi_results = getattr(kpi_assessment, "kpi_results", None) or {}
        for kid, kr in list(kpi_results.items())[:12]:
            bits.append(f"- {getattr(kr,'label','')}: actual={getattr(kr,'actual',None)}, "
                        f"benchmark={getattr(kr,'benchmark',None)}, score={getattr(kr,'score',None)}")
    qre = sess.get("text_qre_confirmed") or {}
    if qre:
        bits.append(f"Confirmed QRE scores: {json.dumps(qre)}")
    discovery = sess.get("discovery_qre") or {}
    if discovery:
        bits.append(f"Discovery answers: {json.dumps(discovery)[:1000]}")
    return "\n".join(bits)


def _build_prompt(sess, force_refresh: bool = False) -> str:
    """Main 5-rule prompt for end-to-end insights generation."""
    context = _build_rich_context(sess)
    return f"""You are an Accenture procurement consultant analysing a maturity assessment.

DATA CONTEXT:
{context}

RULES:
1. Ground every recommendation in the data above. Do not invent metrics.
2. Cite specific KPI gaps (e.g. "TAT 78d vs 45d benchmark") in evidence.
3. Recommendations must be specific actions (not "improve X" — "Roll out catalog buying for top-20 indirect categories").
4. Severity = high if score < 2 OR gap_pct > 50%; medium if 2 ≤ score < 3 OR gap_pct 20-50%; else low.
5. Output STRICT JSON ONLY — no markdown, no commentary outside the JSON.

JSON SCHEMA:
{{
  "summary": "2-3 sentence executive summary of maturity state",
  "strengths": ["bullet points of what's working"],
  "gaps": ["bullet points of biggest gaps with KPI evidence"],
  "priorities": ["top 4 actions for the next 6 months, specific and outcome-linked"],
  "risk_flags": ["operational/compliance/savings risks visible in data"],
  "insight_cards": [
    {{"title": "...", "description": "...", "category": "efficiency|effectiveness|risk|compliance",
      "severity": "high|medium|low", "value": null, "benchmark": null}}
  ]
}}
"""


def _build_tab_prompt(sess, context_name: str) -> str:
    """3 context variants: kpi_overview, rca, offerings."""
    base_context = _build_rich_context(sess)
    if context_name == "kpi_overview":
        focus = "Focus on KPI scorecard interpretation. Explain top 3 KPIs (good and bad) in business terms."
    elif context_name == "rca":
        focus = "Focus on root-cause analysis. For the worst-performing KPIs, hypothesise root causes from data patterns."
    elif context_name == "offerings":
        focus = "Focus on Accenture transformation offerings. Match gaps to Accenture's procurement service portfolio (sourcing-as-a-service, P2P automation, category strategy refresh, supplier risk mgmt)."
    else:
        focus = ""
    return f"""You are an Accenture procurement consultant.

CONTEXT:
{base_context}

{focus}

OUTPUT STRICT JSON:
{{
  "summary": "2-3 sentences",
  "key_points": ["bullet 1","bullet 2","bullet 3"],
  "recommendations": ["specific action 1","action 2"]
}}
"""


def _rule_based_fallback(sess) -> Dict[str, Any]:
    """Rule-based fallback when Vertex AI unavailable."""
    dim_results = sess.get("dim_results") or []
    overall = sess.get("overall_result")
    score = None
    if overall is not None:
        score = getattr(overall, "score", None)
    return {
        "summary": f"Maturity assessment complete with overall score {score or 'N/A'}. AI-generated narrative unavailable; fallback summary used.",
        "strengths": ["Data ingestion completed.", "Baseline KPIs measured."],
        "gaps": ["LLM-driven analysis not available."],
        "priorities": ["Configure Vertex AI ADC to enable AI insights."],
        "risk_flags": [],
        "insight_cards": [],
    }


class AiInsightsPayload(BaseModel):
    force_refresh: bool = False


@router.post("/session/{session_id}/results/ai-insights")
def generate_ai_insights(session_id: str, payload: AiInsightsPayload):
    sess = get_session(session_id)
    if not payload.force_refresh and sess.get("ai_insights"):
        return sess["ai_insights"]
    prompt = _build_prompt(sess, payload.force_refresh)
    raw = _gemini_generate(prompt)
    if raw:
        try:
            data = json.loads(raw)
        except Exception as e:
            data = _rule_based_fallback(sess)
            data["_parse_error"] = str(e)
    else:
        data = _rule_based_fallback(sess)
    sess["ai_insights"] = data
    return data


@router.get("/session/{session_id}/results/ai-insights/status")
def ai_insights_status(session_id: str):
    sess = get_session(session_id)
    return {
        "has_insights": sess.get("ai_insights") is not None,
        "vertex_available": _get_model() is not None,
    }


class AiTabPayload(BaseModel):
    context: str  # kpi_overview, rca, offerings
    force_refresh: bool = False


@router.post("/session/{session_id}/results/ai-tab-insights")
def generate_tab_insights(session_id: str, payload: AiTabPayload):
    sess = get_session(session_id)
    cache_key = f"ai_tab_insights_{payload.context}"
    if not payload.force_refresh and sess.get(cache_key):
        return sess[cache_key]
    prompt = _build_tab_prompt(sess, payload.context)
    raw = _gemini_generate(prompt)
    if raw:
        try:
            data = json.loads(raw)
        except Exception:
            data = {"summary": "AI fallback.", "key_points": [], "recommendations": []}
    else:
        data = {"summary": "Vertex AI unavailable.", "key_points": [], "recommendations": []}
    sess[cache_key] = data
    return data


@router.post("/session/{session_id}/results/ai-buying-categories")
def generate_buying_categories(session_id: str):
    """Gemini-powered material group → buying category structure."""
    sess = get_session(session_id)
    if sess.get("ai_buying_categories"):
        return sess["ai_buying_categories"]
    dfs = sess.get("dataframes") or {}
    po_df = dfs.get("po_df")
    if po_df is None:
        raise HTTPException(status_code=400, detail="No PO data — upload first.")
    col_map = sess.get("final_col_map") or {}
    from routers.kpi_dashboard import _get_po_col
    mg_col = _get_po_col(po_df, "material_group", col_map)
    desc_col = _get_po_col(po_df, "material_group_desc", col_map)
    if not mg_col:
        raise HTTPException(status_code=400, detail="Material group column not found.")
    sample = po_df[[mg_col]].drop_duplicates().head(50).values.tolist()
    prompt = f"""Group the following SAP material groups into 5-7 logical buying categories.

MATERIAL GROUPS:
{sample}

OUTPUT STRICT JSON:
{{
  "categories": [
    {{"name": "...", "description": "...", "material_groups": ["MG001", ...]}}
  ]
}}
"""
    raw = _gemini_generate(prompt)
    if raw:
        try: data = json.loads(raw)
        except Exception: data = {"categories": []}
    else:
        data = {"categories": []}
    sess["ai_buying_categories"] = data
    return data
