#!/usr/bin/env bash
# ─────────────────────────────────────────────────────────────────────────
# setup_gcp.sh — One-shot Google Cloud / Vertex AI setup for ProcAssesment
#
# Configures Application Default Credentials (ADC) so the backend can call
# Vertex AI Gemini without API keys. This uses your free-tier Google Cloud
# account and works on Linux, macOS, and WSL.
#
# Usage:
#   bash scripts/setup_gcp.sh                  # interactive
#   PROJECT_ID=my-proj bash scripts/setup_gcp.sh   # non-interactive
# ─────────────────────────────────────────────────────────────────────────

set -e

echo "──────────────────────────────────────────────────────────────"
echo " ProcAssesment — Google Cloud / Vertex AI setup"
echo "──────────────────────────────────────────────────────────────"

# 1. Check gcloud CLI
if ! command -v gcloud >/dev/null 2>&1; then
  echo "✗ gcloud CLI not found."
  echo ""
  echo "Install it:"
  echo "  Linux:  curl https://sdk.cloud.google.com | bash"
  echo "  macOS:  brew install --cask google-cloud-sdk"
  echo "  WSL:    https://cloud.google.com/sdk/docs/install"
  echo ""
  echo "Then re-run this script."
  exit 1
fi

echo "✓ gcloud CLI found: $(gcloud --version | head -1)"
echo ""

# 2. Auth — login if needed
ACTIVE_ACCOUNT=$(gcloud auth list --filter=status:ACTIVE --format='value(account)' 2>/dev/null | head -1 || true)
if [[ -z "$ACTIVE_ACCOUNT" ]]; then
  echo "→ No active Google account. Opening browser for sign-in..."
  gcloud auth login
else
  echo "✓ Active account: $ACTIVE_ACCOUNT"
fi
echo ""

# 3. Project
if [[ -z "${PROJECT_ID:-}" ]]; then
  CURRENT_PROJECT=$(gcloud config get-value project 2>/dev/null || true)
  if [[ -z "$CURRENT_PROJECT" || "$CURRENT_PROJECT" == "(unset)" ]]; then
    echo "→ Available projects:"
    gcloud projects list --format="table(projectId,name)" --limit=20
    echo ""
    read -p "Enter project ID to use: " PROJECT_ID
  else
    PROJECT_ID="$CURRENT_PROJECT"
    echo "✓ Using project: $PROJECT_ID"
  fi
fi

gcloud config set project "$PROJECT_ID" >/dev/null
echo "✓ Project set: $PROJECT_ID"
echo ""

# 4. Enable Vertex AI API
echo "→ Enabling Vertex AI API..."
gcloud services enable aiplatform.googleapis.com --project="$PROJECT_ID" >/dev/null 2>&1 || true
echo "✓ Vertex AI API enabled"
echo ""

# 5. Application Default Credentials
echo "→ Configuring Application Default Credentials..."
gcloud auth application-default login
gcloud auth application-default set-quota-project "$PROJECT_ID" >/dev/null 2>&1 || true
echo "✓ ADC ready"
echo ""

# 6. Write backend .env
ENV_FILE="$(dirname "$0")/../backend/.env"
mkdir -p "$(dirname "$ENV_FILE")"
cat > "$ENV_FILE" <<EOF
# Auto-generated by scripts/setup_gcp.sh
GEMINI_VERTEX_PROJECT=$PROJECT_ID
GEMINI_VERTEX_LOCATION=us-central1
GEMINI_MODEL=gemini-2.5-pro
EOF

echo "✓ Wrote: $ENV_FILE"
echo ""

# 7. Smoke test
echo "──────────────────────────────────────────────────────────────"
echo " Verifying Vertex AI access..."
echo "──────────────────────────────────────────────────────────────"

python3 -c "
import os
os.environ['GOOGLE_CLOUD_PROJECT'] = '$PROJECT_ID'
try:
    from vertexai import init
    from vertexai.generative_models import GenerativeModel
    init(project='$PROJECT_ID', location='us-central1')
    model = GenerativeModel('gemini-2.5-pro')
    resp = model.generate_content('Say OK if you can read this.')
    print('✓ Vertex AI reachable. Response:', resp.text[:80])
except Exception as e:
    print('✗ Vertex AI test failed:', e)
    print('  → Check that the Vertex AI API is enabled and your account has aiplatform.user role.')
" || true

echo ""
echo "──────────────────────────────────────────────────────────────"
echo " Setup complete!"
echo " Start backend: cd backend && uvicorn main:app --reload --port 8002"
echo " Start frontend: cd frontend && npm install && npm run dev"
echo "──────────────────────────────────────────────────────────────"
